# Generated by Django 4.2 on 2023-04-20 06:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_item_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='kanri',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, verbose_name='管理籍'),
            preserve_default=False,
        ),
    ]
