# Generated by Django 4.2 on 2023-04-20 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_item_kanri'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='zumen',
            field=models.IntegerField(choices=[(1, 'あり'), (2, 'なし')], default=1, verbose_name='図面'),
        ),
    ]
