# Generated by Django 4.2 on 2023-04-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_item_zumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='zumen',
            field=models.IntegerField(choices=[(1, 'あり'), (2, 'なし')], default=1, verbose_name='製品図面'),
        ),
    ]
