# Generated by Django 4.2 on 2023-04-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_item_zumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='created_at',
            field=models.DateTimeField(verbose_name='製造日'),
        ),
    ]
