# Generated by Django 4.1.7 on 2023-04-27 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_item_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kanri',
            field=models.IntegerField(choices=[(1, '道央'), (2, '道南'), (3, '道東'), (4, '道北'), (5, '小樽'), (9, '本社')], default=1, verbose_name='管理籍'),
        ),
    ]
