# Generated by Django 4.1.7 on 2023-04-28 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_item_kanri'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='zumen',
            field=models.BooleanField(choices=[(True, 'あり'), (False, 'なし')], default=True, verbose_name='製品図面'),
        ),
    ]
