# Generated by Django 4.1.7 on 2023-04-28 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_item_zumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='kanri',
            field=models.CharField(choices=[('道央', '道央'), ('道南', '道南'), ('道東', '道東'), ('道北', '道北'), ('小樽', '小樽'), ('本社', '本社')], default='道央', max_length=10, verbose_name='管理籍'),
        ),
    ]
