# Generated by Django 4.1.7 on 2023-05-01 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_item_kanri'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='age',
        ),
        migrations.RemoveField(
            model_name='item',
            name='sex',
        ),
    ]
