# Generated by Django 4.1.7 on 2023-05-06 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_item_hure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hure',
            field=models.CharField(max_length=200, verbose_name='フレーム'),
        ),
    ]
