# Generated by Django 4.1.7 on 2023-05-06 05:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_alter_item_hure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='hure',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(regex='^[a-zA-Z0-9_@\\-\\.]+$')], verbose_name='フレーム'),
        ),
    ]
