# Generated by Django 4.1.7 on 2023-05-06 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_item_hure'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='hoka',
            field=models.BooleanField(choices=[(True, '自社'), (False, '他社')], default=True, verbose_name='他社金型'),
        ),
    ]
