# Generated by Django 4.1.7 on 2023-05-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_item_hoka'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='naka',
            field=models.CharField(default='A859', max_length=200, verbose_name='中型'),
        ),
    ]
