# Generated by Django 4.1.7 on 2023-05-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_item_naka'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='seikei',
            field=models.CharField(default='CD-8', max_length=200, verbose_name='成型機'),
        ),
        migrations.AlterField(
            model_name='item',
            name='naka',
            field=models.CharField(max_length=200, verbose_name='中型'),
        ),
    ]
