# Generated by Django 4.1.7 on 2023-05-06 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_alter_item_idou_alter_item_kotei'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='idou',
            field=models.IntegerField(verbose_name='フレーム高さ移動側'),
        ),
        migrations.AlterField(
            model_name='item',
            name='kotei',
            field=models.IntegerField(verbose_name='フレーム高さ固定側'),
        ),
    ]
