# Generated by Django 4.1.7 on 2023-05-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_alter_item_idou_alter_item_kotei'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='idou',
        ),
        migrations.RemoveField(
            model_name='item',
            name='kotei',
        ),
    ]
