# Generated by Django 4.1.7 on 2023-05-12 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_remove_item_idou_remove_item_kotei'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='idou',
            field=models.IntegerField(default=0, verbose_name='フレーム高さ移動側'),
        ),
        migrations.AddField(
            model_name='item',
            name='kotei',
            field=models.IntegerField(default=0, verbose_name='フレーム高さ固定側'),
        ),
    ]
