# Generated by Django 4.1.7 on 2023-05-15 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_item_idou_item_kotei'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='metuke',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='目付'),
        ),
        migrations.AddField(
            model_name='item',
            name='tori',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=5, verbose_name='取数'),
        ),
    ]
