# Generated by Django 4.1.7 on 2023-05-15 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_item_metuke_item_tori'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='製品名'),
        ),
    ]
